### ISSUE TITLE
Waited 1.5 hours for export. Only audio video is black.

### ISSUE THREAD

**Issue by Crecross** [nasso/urmusic#5]
sucked that I had to wait this long only to not be able to play my video that your beautiful skills made.

**Comment by Nasso** [comment]
Please, provide the error logs and make sure to use the latest version of the app.

Also note thatit is clearly stated that it is currently an alpha and it's not guaranteed to work perfectly on all machines.

**Comment by nasso** [comment]
Yup found out whats wrong, use VLC for now, it should work.

The thing is that urmusic used to render in an uncommon pixel format (Yuv 4:4:4) instead of a more common one (Yuv 4:4:2).
VLC supports both, and youtube automatically converts.
So its fine!

**Comment by Crecross** [comment]
Thank you for figuring that out....I've been using the browser and putting
it in full screen so I can use obs or shadowplay to record it. I had no
Idea I was going to be getting an email 9 months later 😂

On Apr 2, 2018 2:08 PM, "nasso" <notifications@github.com> wrote:

Yup found out whats wrong, use VLC for now, it should work.

The thing is that urmusic used to render in an uncommon pixel format (Yuv
4:4:4) instead of a more common one (Yuv 4:4:2).
VLC supports both, and youtube automatically converts.
So its fine!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nasso/urmusic/issues/5#issuecomment-378047160>, or mute
the thread

**Comment by nasso** [comment]
Thing is i only figured out recently haha!

Imma close the issue now that it's fixed.
