### ISSUE TITLE
How do I load music??

### ISSUE THREAD

**Issue by leemc1989** [nasso/urmusic#6]
How do I load external music so this thing works? like a url or something I have been trying for hours and I can only get the player to load the song but it doesn't play any sound or the visualizer doesn't do nothing..?

**Comment by nasso** [comment]
You can drag and drop a supported audio file from your computer. Or just use the SoundCloud integration in the top right corner, although that will only work for some tracks as not all artists make their tracks available outside of SoundCloud.
