### ISSUE TITLE
Saved .urm file on desktop can't be loaded again

### ISSUE THREAD

**Issue by rareguy** [nasso/urmusic#7]
First of all, thanks for making this visualizer, it's beautiful. I wish I can contribute, but I have yet learned Java in my college.

When I was opening presets, edited it and did "save as" to it on desktop, when I opened it again, the "video size" window didn't pop up and basically didn't load the file. But when I opened the preset file, it loaded as usual. So perhaps the problem is the save format on the urmusic desktop version.

**Comment by nasso** [comment]
Please report issues related to the desktop version on the corresponding repo! This repository corresponds to the web version.

Concerning the issue, please check that you are using the latest version (re-download it to me sure) as i recently worked on a fix to a similar issue.

Also note that the video size dialog doesn't show up for urmusic projects saved from urmusic 4, as the video size is stored in the file.

Thanks for your report!

**Comment by rareguy** [comment]
Ah, sorry. I thought there were only one repo, urmusic.

Where can I download it? I can't seem to find the application..

**Comment by nasso** [comment]
https://github.com/nasso/urmusic-desktop

There are the releases.
